package CompanyMVC;


/**
 *
 * @author shaemcfadden
 */
public class EmployeeGUI extends javax.swing.JFrame {
    
    private final String[] POSL = new String[] {"Plant Worker", 
        "R&D Scientist", "Engineer", "Computer Scientist", "Sales", "Manager", 
        "CTO", "COO", "Lawyer", "Marketing"}; //all positions
    private final String[] CITL = new String[] {"New York", 
        "Silicon Vally", "Ottawa", "Beijing"}; //all cities
    
    private final String[] NYPOS = new String[] {"Sales", "Manager", 
        "CTO", "COO", "Lawyer", "Marketing"}; //positions in New York
    private final String[] SVPOS = new String[] {"R&D Scientist", "Engineer", 
        "Computer Scientist"}; //positions in silicon valley
    private final String[] OPOS = new String[] {"Computer Scientist", "Sales", 
        "Marketing"}; //positions in Ottawa
    private final String[] BPOS = new String[] {"Plant Worker", "Engineer", 
        "Manager"}; //positions in Beijing
    
    //Default setting: first is min, second is max,
    //third is major tics, fourth is minor tics
    private final int[] SAL = new int[] {50000, 80000, 10000, 1000};
    //plant worker Salary: first is min, second is max,
    //third is major tics, fourth is minor tics
    private final int[] PWSAL = new int[] {20000, 30000, 1000, 500};
    //R&D scientist Salary: first is min, second is max
    //third is major tics, fourth is minor tics
    private final int[] RDSAL = new int[] {80000, 90000, 1000, 500};
    //Engineer Salary: first is min, second is max
    //third is major tics, fourth is minor tics
    private final int[] ESAL = new int[] {50000, 130000, 10000, 5000};
    //Comp Sci Salary: first is min, second is max
    //third is major tics, fourth is minor tics
    private final int[] CSSAL = new int[] {75000, 140000, 10000, 500};
    //Sales Salary: first is min, second is max
    //third is major tics, fourth is minor tics
    private final int[] SSAL = new int[] {40000, 80000, 5000, 2500};
    //Manager Salary: first is min, second is max
    //third is major tics, fourth is minor tics
    private final int[] MASAL = new int[] {80000, 100000, 2000, 1000};
    //CTO Salary: first is min, second is max
    //third is major tics, fourth is minor tics
    private final int[] CTOSAL = new int[] {200000, 280000, 10000, 5000};
    //COO Salary: first is min, second is max
    //third is major tics, fourth is minor tics
    private final int[] COOSAL = new int[] {340000, 580000, 40000, 20000};
    //Lawyer Salary: first is min, second is max
    //third is major tics, fourth is minor tics
    private final int[] LSAL = new int[] {80000, 120000, 5000, 2500};
    //Marketing Salary: first is min, second is max
    //third is major tics, fourth is minor tics
    private final int[] MKSAL = new int[] {50000, 70000, 2000, 1000};
    
    private String Ci = ""; //string for city designation
    private String Po = ""; //string for position designation
    
    /**
     * Creates new form EmployeeGUI
     */
    
    public EmployeeGUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        SearchRB = new javax.swing.ButtonGroup();
        EmployeePanel = new javax.swing.JPanel();
        ApplicationLabel = new javax.swing.JLabel();
        LastNameLabel = new javax.swing.JLabel();
        FirstNameLabel = new javax.swing.JLabel();
        FirstNameTxt = new javax.swing.JTextField();
        LastNameTxt = new javax.swing.JTextField();
        CityLabel = new javax.swing.JLabel();
        CityCombo = new javax.swing.JComboBox<>();
        PositionCombo = new javax.swing.JComboBox<>();
        PositionLabel = new javax.swing.JLabel();
        SalaryLabel = new javax.swing.JLabel();
        SalarySlider = new javax.swing.JSlider();
        SubmitBtn = new javax.swing.JButton();
        ClearBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Company");

        EmployeePanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        EmployeePanel.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        ApplicationLabel.setText("  Application");
        ApplicationLabel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        LastNameLabel.setText(" Last Name");
        LastNameLabel.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        FirstNameLabel.setText(" First Name");
        FirstNameLabel.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        FirstNameTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FirstNameTxtActionPerformed(evt);
            }
        });

        LastNameTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LastNameTxtActionPerformed(evt);
            }
        });

        CityLabel.setText(" City ");
        CityLabel.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        CityCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select One", "New York", "Silicon Vally", "Ottawa", "Beijing" }));
        CityCombo.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                CityComboItemStateChanged(evt);
            }
        });
        CityCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CityComboActionPerformed(evt);
            }
        });

        PositionCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select One", "Plant Worker", "R&D Scientist", "Engineer", "Computer Scientist", "Sales", "Manager", "CTO", "COO", "Lawyer", "Marketing" }));
        PositionCombo.setEnabled(false);
        PositionCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PositionComboActionPerformed(evt);
            }
        });

        PositionLabel.setText(" Position ");
        PositionLabel.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        SalaryLabel.setText(" Salary ");
        SalaryLabel.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        SalarySlider.setMajorTickSpacing(10000);
        SalarySlider.setMaximum(80000);
        SalarySlider.setMinimum(50000);
        SalarySlider.setMinorTickSpacing(1000);
        SalarySlider.setOrientation(javax.swing.JSlider.VERTICAL);
        SalarySlider.setPaintLabels(true);
        SalarySlider.setPaintTicks(true);
        SalarySlider.setSnapToTicks(true);
        SalarySlider.setEnabled(false);

        SubmitBtn.setText("Submit");
        SubmitBtn.setToolTipText("");
        SubmitBtn.setEnabled(false);
        SubmitBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SubmitBtnActionPerformed(evt);
            }
        });

        ClearBtn.setText("Clear");
        ClearBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ClearBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout EmployeePanelLayout = new javax.swing.GroupLayout(EmployeePanel);
        EmployeePanel.setLayout(EmployeePanelLayout);
        EmployeePanelLayout.setHorizontalGroup(
            EmployeePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(EmployeePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(EmployeePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(EmployeePanelLayout.createSequentialGroup()
                        .addComponent(ApplicationLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(EmployeePanelLayout.createSequentialGroup()
                        .addGroup(EmployeePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(EmployeePanelLayout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(SalaryLabel)
                                .addGap(72, 72, 72)
                                .addComponent(FirstNameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(EmployeePanelLayout.createSequentialGroup()
                                .addComponent(SalarySlider, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addGroup(EmployeePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(FirstNameTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(LastNameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(LastNameTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(CityLabel)
                                    .addComponent(CityCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(PositionLabel)
                                    .addComponent(PositionCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(EmployeePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(ClearBtn, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(SubmitBtn, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                        .addGap(22, 22, 22))))
        );
        EmployeePanelLayout.setVerticalGroup(
            EmployeePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(EmployeePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(ApplicationLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(EmployeePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(FirstNameLabel)
                    .addComponent(SalaryLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(EmployeePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(EmployeePanelLayout.createSequentialGroup()
                        .addComponent(FirstNameTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(LastNameLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(LastNameTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(CityLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(CityCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(PositionLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(PositionCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(SubmitBtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ClearBtn))
                    .addComponent(SalarySlider, javax.swing.GroupLayout.PREFERRED_SIZE, 352, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(26, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(EmployeePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 438, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(EmployeePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    
    private void LastNameTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LastNameTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_LastNameTxtActionPerformed

    private void FirstNameTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FirstNameTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FirstNameTxtActionPerformed

    private void PositionComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PositionComboActionPerformed
        System.out.println("Position Action Performed");
        if (PositionCombo.getSelectedItem().toString().equals("Select One")){
            SetSlider(SAL); //sets back to default
            SalarySlider.setEnabled(false); //disables salary slider
            SubmitBtn.setEnabled(false); //disables submit button
        }//end of if postion combo equals Select One
        
        if (PositionCombo.getSelectedItem().toString().equals("Plant Worker")){
            SetSlider(PWSAL); //sets slider with plant worker values
            SalarySlider.setEnabled(true); //enables salary slider
            SubmitBtn.setEnabled(true); //enables submit button
            
            Po = "PW";//sets position designation
        }//end of if postion combo equals plant worker
        
        else if (PositionCombo.getSelectedItem().toString().equals("R&D Scientist")){
            SetSlider(RDSAL); //sets slider with R&D Scientist values
            SalarySlider.setEnabled(true); //enables salary slider
            SubmitBtn.setEnabled(true);//enables submit button
            
            Po = "RD";//sets position designation
        }//end of if postion combo equals R&D Scientist
        
        else if (PositionCombo.getSelectedItem().toString().equals("Engineer")){
            SetSlider(ESAL); //sets slider with Engineer values
            SalarySlider.setEnabled(true); //enables salary slider
            SubmitBtn.setEnabled(true);//enables submit button
            
            Po = "E";//sets position designation
        }//end of if postion combo equals Engineer
        
        else if (PositionCombo.getSelectedItem().toString().equals("Computer Scientist")){
            SetSlider(CSSAL); //sets slider with Computer Scientist values
            SalarySlider.setEnabled(true); //enables salary slider
            SubmitBtn.setEnabled(true);//enables submit button
            
            Po = "CS";//sets position designation
        }//end of if postion combo equals Computer Scientist
        
        else if (PositionCombo.getSelectedItem().toString().equals("Sales")){
            SetSlider(SSAL); //sets slider with Sales values
            SalarySlider.setEnabled(true); //enables salary slider
            SubmitBtn.setEnabled(true);//enables submit button
            
            Po = "S";//sets position designation
        }//end of if postion combo equals Sales
        
        else if (PositionCombo.getSelectedItem().toString().equals("Manager")){
            SetSlider(MASAL); //sets slider with Manager values
            SalarySlider.setEnabled(true); //enables salary slider
            SubmitBtn.setEnabled(true);//enables submit button
            
            Po = "MA";//sets position designation
        }//end of if postion combo equals Manager
        
        else if (PositionCombo.getSelectedItem().toString().equals("CTO")){
            SetSlider(CTOSAL); //sets slider with CTO values
            SalarySlider.setEnabled(true); //enables salary slider
            SubmitBtn.setEnabled(true);//enables submit button
            
            Po = "CTO";//sets position designation
        }//end of if postion combo equals CTO
        
        else if (PositionCombo.getSelectedItem().toString().equals("COO")){
            SetSlider(COOSAL); //sets slider with COO values
            SalarySlider.setEnabled(true); //enables salary slider
            SubmitBtn.setEnabled(true);//enables submit button
            
            Po = "COO";//sets position designation
        }//end of if postion combo equals COO
        
        else if (PositionCombo.getSelectedItem().toString().equals("Lawyer")){
            SetSlider(LSAL); //sets slider with Lawyer values
            SalarySlider.setEnabled(true); //enables salary slider
            SubmitBtn.setEnabled(true);//enables submit button
            
            Po = "L";//sets position designation
        }//end of if postion combo equals Lawyer
        
        else{
            SetSlider(MKSAL); //sets slider with Marketing values
            SalarySlider.setEnabled(true); //enables salary slider
            SubmitBtn.setEnabled(true);//enables submit button
            
            Po = "MK"; //sets position designation
        }//end of else postion combo equals Marketing
        
    }//GEN-LAST:event_PositionComboActionPerformed

    private void CityComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CityComboActionPerformed
        
    }//GEN-LAST:event_CityComboActionPerformed

    private void CityComboItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_CityComboItemStateChanged
        System.out.println("ACTION PERFORMED");
        if (CityCombo.getSelectedItem().toString().equals("Select One")){
            PositionCombo.setSelectedIndex(0); //sets back to default
            PositionCombo.setEnabled(false); //disables
        }//end of if first combo equals Select One
        
        else if (CityCombo.getSelectedItem().toString().equals("New York")){
            ResetPositionCombo(NYPOS); //resets combo with NY Value
          PositionCombo.setEnabled(true); //allows access to second box
          
          Ci = "NY"; //sets city designation
        }//end of if New York
        
        else if (CityCombo.getSelectedItem().toString().equals("Silicon Vally")){
          ResetPositionCombo(SVPOS); //resets combo with Silicon Valley Value
          PositionCombo.setEnabled(true); //allows access to second box
          
          Ci = "SV";//sets city designation
        }//end of if Silicon Vally
        
        else if (CityCombo.getSelectedItem().toString().equals("Ottawa")){
          ResetPositionCombo(OPOS); //resets combo with ottawa value
          PositionCombo.setEnabled(true); //allows access to second box
          
          Ci = "O";//sets city designation
        }//end of if Ottawa
        
        else if (CityCombo.getSelectedItem().toString().equals("Beijing")){
          ResetPositionCombo(BPOS); //resets combo with Beijing value
          PositionCombo.setEnabled(true); //allows access to second box
          
          Ci = "B";//sets city designation
        }//end of if Beijing

    }//GEN-LAST:event_CityComboItemStateChanged

    private void ClearBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ClearBtnActionPerformed
       ResetInputs(); //resets inputs
    }//GEN-LAST:event_ClearBtnActionPerformed

    private void SubmitBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SubmitBtnActionPerformed
        String firstName = FirstNameTxt.getText(); //holds employee's first name
        String lastName = LastNameTxt.getText(); //holds employee's last name
    
        String city = ""; //holds employee's city
        String position = ""; //holds employee's position
        
        int salary = SalarySlider.getValue(); //holds employee's salary
        
        ResetInputs(); //resets/clears inputs
    }//GEN-LAST:event_SubmitBtnActionPerformed
    
    private void ResetCityCombo(){
        System.out.println("FIRST COMBO RESET");
        int len = CityCombo.getItemCount()-1;//variable for number of cities in combo box
        
        for(int i = 0; i<len; i++){
            System.out.println(CityCombo.getItemCount());
            CityCombo.removeItemAt(1);
        }
        for(int i = 0; i<CITL.length; i++)
            CityCombo.addItem(CITL[i]);
    }//end of ResetCityCombo
    
    private void ResetPositionCombo(String[] p){
        System.out.println("SECOND COMBO RESET");
        int len = PositionCombo.getItemCount()-1;//variable for number of positions in combo box
        
        for(int i = 0; i<len; i++)
           PositionCombo.removeItemAt(1);
        
        for(int i = 0; i<p.length; i++)
            PositionCombo.addItem(p[i]);
    }//end of ResetPositionCombo
    
    private void ResetNames(){
        FirstNameTxt.setText("");//resets first name field
        LastNameTxt.setText(""); // resets last name field
    }//end of resetNames
    
    private void SetSlider (int[] sv){
        int mid = (sv[0] + sv[1])/2;
        
        SalarySlider.setMinimum(sv[0]); //sets min salary for slider
        SalarySlider.setMaximum(sv[1]); //sets max salary for slider

        SalarySlider.setMajorTickSpacing(sv[2]); //sets major tick spacing 
        SalarySlider.setMinorTickSpacing(sv[3]); //sets minor tick spacing
        //sets the labels on slider
        SalarySlider.setLabelTable(SalarySlider.createStandardLabels(sv[2]));
        
        SalarySlider.setValue(mid);//sets pointer at mid point
    }//end of SetSlider
    
    private void ResetInputs(){
       ResetCityCombo(); //resets city combo box
       ResetPositionCombo(POSL); //resets psoition combo box
       ResetNames(); //resets name fields
       SetSlider(SAL); //resets slider
    }//end of reset inputs
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EmployeeGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EmployeeGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EmployeeGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EmployeeGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EmployeeGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ApplicationLabel;
    private javax.swing.JComboBox<String> CityCombo;
    private javax.swing.JLabel CityLabel;
    private javax.swing.JButton ClearBtn;
    private javax.swing.JPanel EmployeePanel;
    private javax.swing.JLabel FirstNameLabel;
    private javax.swing.JTextField FirstNameTxt;
    private javax.swing.JLabel LastNameLabel;
    private javax.swing.JTextField LastNameTxt;
    private javax.swing.JComboBox<String> PositionCombo;
    private javax.swing.JLabel PositionLabel;
    private javax.swing.JLabel SalaryLabel;
    private javax.swing.JSlider SalarySlider;
    private javax.swing.ButtonGroup SearchRB;
    private javax.swing.JButton SubmitBtn;
    // End of variables declaration//GEN-END:variables
}
