package CompanyMVC;

import java.util.ArrayList;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;


/**
 *
 * @author shaemcfadden
 */
public class EmployeeGUI extends javax.swing.JFrame {
    
    private final String[] POSL = new String[] {"Plant Worker", 
        "R&D Scientist", "Engineer", "Computer Scientist", "Sales", "Manager", 
        "CTO", "COO", "Lawyer", "Marketing"}; //all positions
    private final String[] CITL = new String[] {"New York", 
        "Silicon Valley", "Ottawa", "Beijing"}; //all cities
    
    private final String[] NYPOS = new String[] {"Sales", "Manager", 
        "CTO", "COO", "Lawyer", "Marketing"}; //positions in New York
    private final String[] SVPOS = new String[] {"R&D Scientist", "Engineer", 
        "Computer Scientist"}; //positions in silicon valley
    private final String[] OPOS = new String[] {"Computer Scientist", "Sales", 
        "Marketing"}; //positions in Ottawa
    private final String[] BPOS = new String[] {"Plant Worker", "Engineer", 
        "Manager"}; //positions in Beijing
    
    //Default setting: first is min, second is max,
    //third is major tics, fourth is minor tics
    private final int[] SAL = new int[] {50000, 80000, 10000, 1000};
    //plant worker Salary: first is min, second is max,
    //third is major tics, fourth is minor tics
    private final int[] PWSAL = new int[] {20000, 30000, 1000, 500};
    //R&D scientist Salary: first is min, second is max
    //third is major tics, fourth is minor tics
    private final int[] RDSAL = new int[] {80000, 90000, 1000, 500};
    //Engineer Salary: first is min, second is max
    //third is major tics, fourth is minor tics
    private final int[] ESAL = new int[] {50000, 130000, 10000, 5000};
    //Comp Sci Salary: first is min, second is max
    //third is major tics, fourth is minor tics
    private final int[] CSSAL = new int[] {75000, 140000, 5000, 2500};
    //Sales Salary: first is min, second is max
    //third is major tics, fourth is minor tics
    private final int[] SSAL = new int[] {40000, 80000, 5000, 2500};
    //Manager Salary: first is min, second is max
    //third is major tics, fourth is minor tics
    private final int[] MASAL = new int[] {80000, 100000, 2000, 1000};
    //CTO Salary: first is min, second is max
    //third is major tics, fourth is minor tics
    private final int[] CTOSAL = new int[] {200000, 280000, 10000, 5000};
    //COO Salary: first is min, second is max
    //third is major tics, fourth is minor tics
    private final int[] COOSAL = new int[] {340000, 580000, 40000, 20000};
    //Lawyer Salary: first is min, second is max
    //third is major tics, fourth is minor tics
    private final int[] LSAL = new int[] {80000, 120000, 5000, 2500};
    //Marketing Salary: first is min, second is max
    //third is major tics, fourth is minor tics
    private final int[] MKSAL = new int[] {50000, 70000, 2000, 1000};
    
    protected Controller con;//links GUI to controller
    //list that will be repersented as the list on the gui
    protected DefaultListModel employeeListModel = new DefaultListModel();
    
    private String Ci = ""; //string for city designation
    private String Po = ""; //string for position designation
    
    private boolean AllSaved = true; //boolean for if all shown data is saved
    
    /**
     * Creates new form EmployeeGUI
     */
    
    public EmployeeGUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        SearchRB = new javax.swing.ButtonGroup();
        EmployeePanel = new javax.swing.JPanel();
        ApplicationLabel = new javax.swing.JLabel();
        LastNameLabel = new javax.swing.JLabel();
        FirstNameLabel = new javax.swing.JLabel();
        FirstNameTxt = new javax.swing.JTextField();
        LastNameTxt = new javax.swing.JTextField();
        CityLabel = new javax.swing.JLabel();
        CityCombo = new javax.swing.JComboBox<>();
        PositionCombo = new javax.swing.JComboBox<>();
        PositionLabel = new javax.swing.JLabel();
        SalaryLabel = new javax.swing.JLabel();
        SalarySlider = new javax.swing.JSlider();
        SubmitBtn = new javax.swing.JButton();
        ClearBtn = new javax.swing.JButton();
        InfoPanel = new javax.swing.JPanel();
        InfoPanelLabel = new javax.swing.JLabel();
        EmployeeListScrollPane = new javax.swing.JScrollPane();
        EmployeeList = new javax.swing.JList<>();
        EmployeeListLabel = new javax.swing.JLabel();
        EmployeeDetailScrollPane = new javax.swing.JScrollPane();
        EmployeeDetailTxt = new javax.swing.JTextArea();
        EmployeeDetailLabel = new javax.swing.JLabel();
        SaveBtn = new javax.swing.JButton();
        InformationControlsLabel = new javax.swing.JLabel();
        LoadBtn = new javax.swing.JButton();
        RemoveBtn = new javax.swing.JButton();
        EditBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Company");

        EmployeePanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        EmployeePanel.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        ApplicationLabel.setText("  Application");
        ApplicationLabel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        LastNameLabel.setText(" Last Name");
        LastNameLabel.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        FirstNameLabel.setText(" First Name");
        FirstNameLabel.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        FirstNameTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FirstNameTxtActionPerformed(evt);
            }
        });

        LastNameTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LastNameTxtActionPerformed(evt);
            }
        });

        CityLabel.setText(" City ");
        CityLabel.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        CityCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select One", "New York", "Silicon Valley", "Ottawa", "Beijing" }));
        CityCombo.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                CityComboItemStateChanged(evt);
            }
        });
        CityCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CityComboActionPerformed(evt);
            }
        });

        PositionCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select One", "Plant Worker", "R&D Scientist", "Engineer", "Computer Scientist", "Sales", "Manager", "CTO", "COO", "Lawyer", "Marketing" }));
        PositionCombo.setEnabled(false);
        PositionCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PositionComboActionPerformed(evt);
            }
        });

        PositionLabel.setText(" Position ");
        PositionLabel.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        SalaryLabel.setText(" Salary ");
        SalaryLabel.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        SalarySlider.setMajorTickSpacing(10000);
        SalarySlider.setMaximum(80000);
        SalarySlider.setMinimum(50000);
        SalarySlider.setMinorTickSpacing(1000);
        SalarySlider.setOrientation(javax.swing.JSlider.VERTICAL);
        SalarySlider.setPaintLabels(true);
        SalarySlider.setPaintTicks(true);
        SalarySlider.setSnapToTicks(true);
        SalarySlider.setEnabled(false);

        SubmitBtn.setText("Submit");
        SubmitBtn.setToolTipText("");
        SubmitBtn.setEnabled(false);
        SubmitBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SubmitBtnActionPerformed(evt);
            }
        });

        ClearBtn.setText("Clear");
        ClearBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ClearBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout EmployeePanelLayout = new javax.swing.GroupLayout(EmployeePanel);
        EmployeePanel.setLayout(EmployeePanelLayout);
        EmployeePanelLayout.setHorizontalGroup(
            EmployeePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(EmployeePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(EmployeePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(EmployeePanelLayout.createSequentialGroup()
                        .addComponent(ApplicationLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(EmployeePanelLayout.createSequentialGroup()
                        .addGroup(EmployeePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(EmployeePanelLayout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(SalaryLabel)
                                .addGap(72, 72, 72)
                                .addComponent(FirstNameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(EmployeePanelLayout.createSequentialGroup()
                                .addComponent(SalarySlider, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addGroup(EmployeePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(FirstNameTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(LastNameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(LastNameTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(CityLabel)
                                    .addComponent(CityCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(PositionLabel)
                                    .addComponent(PositionCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(EmployeePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(ClearBtn, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(SubmitBtn, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                        .addGap(22, 22, 22))))
        );
        EmployeePanelLayout.setVerticalGroup(
            EmployeePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(EmployeePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(ApplicationLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(EmployeePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(FirstNameLabel)
                    .addComponent(SalaryLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(EmployeePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(EmployeePanelLayout.createSequentialGroup()
                        .addComponent(FirstNameTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(LastNameLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(LastNameTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(CityLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(CityCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(PositionLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(PositionCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(SubmitBtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ClearBtn))
                    .addComponent(SalarySlider, javax.swing.GroupLayout.PREFERRED_SIZE, 352, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        InfoPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        InfoPanelLabel.setText(" Employee Information ");
        InfoPanelLabel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        EmployeeList.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        EmployeeList.setModel(employeeListModel);
        EmployeeList.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                EmployeeListValueChanged(evt);
            }
        });
        EmployeeListScrollPane.setViewportView(EmployeeList);

        EmployeeListLabel.setText("Employee List");

        EmployeeDetailScrollPane.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        EmployeeDetailTxt.setColumns(20);
        EmployeeDetailTxt.setRows(5);
        EmployeeDetailScrollPane.setViewportView(EmployeeDetailTxt);

        EmployeeDetailLabel.setText("Employee Detail");

        SaveBtn.setText("Save list");
        SaveBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SaveBtnActionPerformed(evt);
            }
        });

        InformationControlsLabel.setText("Employee Information Controls");

        LoadBtn.setText("Load List");
        LoadBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LoadBtnActionPerformed(evt);
            }
        });

        RemoveBtn.setText("Remove Employee");
        RemoveBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RemoveBtnActionPerformed(evt);
            }
        });

        EditBtn.setText("Edit Employee");

        javax.swing.GroupLayout InfoPanelLayout = new javax.swing.GroupLayout(InfoPanel);
        InfoPanel.setLayout(InfoPanelLayout);
        InfoPanelLayout.setHorizontalGroup(
            InfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(InfoPanelLayout.createSequentialGroup()
                .addGroup(InfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(InfoPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(InfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(InfoPanelLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(EmployeeListScrollPane)
                            .addComponent(EmployeeDetailScrollPane)))
                    .addGroup(InfoPanelLayout.createSequentialGroup()
                        .addGroup(InfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(InfoPanelLayout.createSequentialGroup()
                                .addGap(212, 212, 212)
                                .addComponent(EmployeeListLabel))
                            .addGroup(InfoPanelLayout.createSequentialGroup()
                                .addGap(205, 205, 205)
                                .addComponent(EmployeeDetailLabel))
                            .addGroup(InfoPanelLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(SaveBtn)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(LoadBtn)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(RemoveBtn)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(EditBtn)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(InfoPanelLayout.createSequentialGroup()
                .addGap(152, 152, 152)
                .addComponent(InformationControlsLabel)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        InfoPanelLayout.setVerticalGroup(
            InfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(InfoPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(InfoPanelLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(EmployeeListLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(EmployeeListScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(EmployeeDetailLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(EmployeeDetailScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(InformationControlsLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(InfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SaveBtn)
                    .addComponent(LoadBtn)
                    .addComponent(RemoveBtn)
                    .addComponent(EditBtn))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(EmployeePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(InfoPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(EmployeePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(InfoPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    
    private void LastNameTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LastNameTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_LastNameTxtActionPerformed

    private void FirstNameTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FirstNameTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FirstNameTxtActionPerformed

    private void PositionComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PositionComboActionPerformed
        if (PositionCombo.getSelectedItem().toString().equals("Select One")){
            SetSlider(SAL); //sets back to default
            SalarySlider.setEnabled(false); //disables salary slider
            SubmitBtn.setEnabled(false); //disables submit button
        }//end of if postion combo equals Select One
        
        else if (PositionCombo.getSelectedItem().toString().equals("Plant Worker")){
            SetSlider(PWSAL); //sets slider with plant worker values
            SalarySlider.setEnabled(true); //enables salary slider
            SubmitBtn.setEnabled(true); //enables submit button
            
            Po = "PW";//sets position designation
        }//end of if postion combo equals plant worker
        
        else if (PositionCombo.getSelectedItem().toString().equals("R&D Scientist")){
            SetSlider(RDSAL); //sets slider with R&D Scientist values
            SalarySlider.setEnabled(true); //enables salary slider
            SubmitBtn.setEnabled(true);//enables submit button
            
            Po = "RD";//sets position designation
        }//end of if postion combo equals R&D Scientist
        
        else if (PositionCombo.getSelectedItem().toString().equals("Engineer")){
            SetSlider(ESAL); //sets slider with Engineer values
            SalarySlider.setEnabled(true); //enables salary slider
            SubmitBtn.setEnabled(true);//enables submit button
            
            Po = "E";//sets position designation
        }//end of if postion combo equals Engineer
        
        else if (PositionCombo.getSelectedItem().toString().equals("Computer Scientist")){
            SetSlider(CSSAL); //sets slider with Computer Scientist values
            SalarySlider.setEnabled(true); //enables salary slider
            SubmitBtn.setEnabled(true);//enables submit button
            
            Po = "CS";//sets position designation
        }//end of if postion combo equals Computer Scientist
        
        else if (PositionCombo.getSelectedItem().toString().equals("Sales")){
            SetSlider(SSAL); //sets slider with Sales values
            SalarySlider.setEnabled(true); //enables salary slider
            SubmitBtn.setEnabled(true);//enables submit button
            
            Po = "S";//sets position designation
        }//end of if postion combo equals Sales
        
        else if (PositionCombo.getSelectedItem().toString().equals("Manager")){
            SetSlider(MASAL); //sets slider with Manager values
            SalarySlider.setEnabled(true); //enables salary slider
            SubmitBtn.setEnabled(true);//enables submit button
            
            Po = "MA";//sets position designation
        }//end of if postion combo equals Manager
        
        else if (PositionCombo.getSelectedItem().toString().equals("CTO")){
            SetSlider(CTOSAL); //sets slider with CTO values
            SalarySlider.setEnabled(true); //enables salary slider
            SubmitBtn.setEnabled(true);//enables submit button
            
            Po = "CTO";//sets position designation
        }//end of if postion combo equals CTO
        
        else if (PositionCombo.getSelectedItem().toString().equals("COO")){
            SetSlider(COOSAL); //sets slider with COO values
            SalarySlider.setEnabled(true); //enables salary slider
            SubmitBtn.setEnabled(true);//enables submit button
            
            Po = "COO";//sets position designation
        }//end of if postion combo equals COO
        
        else if (PositionCombo.getSelectedItem().toString().equals("Lawyer")){
            SetSlider(LSAL); //sets slider with Lawyer values
            SalarySlider.setEnabled(true); //enables salary slider
            SubmitBtn.setEnabled(true);//enables submit button
            
            Po = "L";//sets position designation
        }//end of if postion combo equals Lawyer
        
        else{
            SetSlider(MKSAL); //sets slider with Marketing values
            SalarySlider.setEnabled(true); //enables salary slider
            SubmitBtn.setEnabled(true);//enables submit button
            
            Po = "MK"; //sets position designation
        }//end of else postion combo equals Marketing
        
    }//GEN-LAST:event_PositionComboActionPerformed

    private void CityComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CityComboActionPerformed
        
    }//GEN-LAST:event_CityComboActionPerformed

    private void CityComboItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_CityComboItemStateChanged
        if (CityCombo.getSelectedItem().toString().equals("Select One")){
            PositionCombo.setSelectedIndex(0); //sets back to default
            PositionCombo.setEnabled(false); //disables
        }//end of if first combo equals Select One
        
        else if (CityCombo.getSelectedItem().toString().equals("New York")){
            ResetPositionCombo(NYPOS); //resets combo with NY Value
          PositionCombo.setEnabled(true); //allows access to second box
          
          Ci = "NY"; //sets city designation
        }//end of if New York
        
        else if (CityCombo.getSelectedItem().toString().equals("Silicon Valley")){
          ResetPositionCombo(SVPOS); //resets combo with Silicon Valley Value
          PositionCombo.setEnabled(true); //allows access to second box
          
          Ci = "SV";//sets city designation
        }//end of if Silicon Vally
        
        else if (CityCombo.getSelectedItem().toString().equals("Ottawa")){
          ResetPositionCombo(OPOS); //resets combo with ottawa value
          PositionCombo.setEnabled(true); //allows access to second box
          
          Ci = "OT";//sets city designation
        }//end of if Ottawa
        
        else if (CityCombo.getSelectedItem().toString().equals("Beijing")){
          ResetPositionCombo(BPOS); //resets combo with Beijing value
          PositionCombo.setEnabled(true); //allows access to second box
          
          Ci = "BI";//sets city designation
        }//end of if Beijing

    }//GEN-LAST:event_CityComboItemStateChanged

    private void ClearBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ClearBtnActionPerformed
       ResetInputs(); //resets inputs
    }//GEN-LAST:event_ClearBtnActionPerformed

    private void SubmitBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SubmitBtnActionPerformed
        String firstName = FirstNameTxt.getText(); //holds employee's first name
        String lastName = LastNameTxt.getText(); //holds employee's last name
    
        String city = ""; //holds employee's city
        String position = ""; //holds employee's position
        
        double salary = SalarySlider.getValue(); //holds employee's salary
        
        //sends data to controller
        con.submitButtonClicked(firstName, lastName, Ci, Po, salary);
        
        AllSaved = false; //new employee has been added so all is not saved
        ResetInputs(); //resets/clears inputs
    }//GEN-LAST:event_SubmitBtnActionPerformed

    private void SaveBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SaveBtnActionPerformed
        con.writeEmployeeList(); //save the employee
        AllSaved = true; //sets all saved to true since data was just saved
    }//GEN-LAST:event_SaveBtnActionPerformed

    private void EmployeeListValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_EmployeeListValueChanged
        
        int n = EmployeeList.getSelectedIndex(); //gets employee selected
         
        if (n==-1){ //if nothing is selected index equals -1
             //clears info screen when nothing is selected
             EmployeeDetailTxt.setText(""); 
         }//end of if sentienl value
         else{
        EmployeeDetailTxt.setText(con.getEmployee(n)); //shows info on selected employee
         }//end of else
        
    }//GEN-LAST:event_EmployeeListValueChanged

    private void LoadBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LoadBtnActionPerformed
       //acts as a sentinel value since confirmation message returns 0 for yes
       int confirm = 0; 
        
        if (AllSaved){
           confirm = 0; //sets confirm so load will occur
       }//end of if there is no unsaved data
        else{
        confirm = JOptionPane.showConfirmDialog(null, "All Unsaved Data "
               + "Will Be Deleted.\nDo You Wish To Continue?", "Confirmation", 
               JOptionPane.YES_NO_OPTION);
        }//else if there is unsaved data
        
       if (confirm == 0){
        con.getEmployeeList(); //gets employee list
        AllSaved = true; //list has been reloaded so only saved values show
       }//end of if confirmed
    }//GEN-LAST:event_LoadBtnActionPerformed

    private void RemoveBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RemoveBtnActionPerformed
        
        int n = EmployeeList.getSelectedIndex(); //gets employee selected
        
        con.employees.remove(n); //removes selected employee from controller array
        employeeListModel.remove(n); //removes selected employee from list
        
        AllSaved = false; //employee values have been change
        
        resetIDS();
        
    }//GEN-LAST:event_RemoveBtnActionPerformed
    
    //*****************************************************
    // Purpose: resets city combo box
    // Interface: IN: na
    // Returns: na
    // *****************************************************
    private void ResetCityCombo(){
        int len = CityCombo.getItemCount()-1;//variable for number of cities in combo box
        
        for(int i = 0; i<len; i++){
            CityCombo.removeItemAt(1); //removes citys from box
        }
        for(int i = 0; i<CITL.length; i++)
            CityCombo.addItem(CITL[i]); //adds new cities to box
    }//end of ResetCityCombo
    
    //*****************************************************
    // Purpose: resets position combo box
    // Interface: IN: position array
    // Returns: na
    // *****************************************************
    private void ResetPositionCombo(String[] p){
        int len = PositionCombo.getItemCount()-1;//variable for number of positions in combo box
        
        for(int i = 0; i<len; i++)
           PositionCombo.removeItemAt(1); //removes positions from box
        
        for(int i = 0; i<p.length; i++)
            PositionCombo.addItem(p[i]); //adds new positions to box
    }//end of ResetPositionCombo
    
    //*****************************************************
    // Purpose: resets name fields
    // Interface: IN: na
    // Returns: na
    // *****************************************************
    private void ResetNames(){
        FirstNameTxt.setText("");//resets first name field
        LastNameTxt.setText(""); // resets last name field
    }//end of resetNames
    
    //*****************************************************
    // Purpose: sets up slider and labels for slider
    // Interface: IN: salary array
    // Returns: na
    // *****************************************************
    private void SetSlider (int[] sv){
        int mid = (sv[0] + sv[1])/2;
        
        SalarySlider.setMinimum(sv[0]); //sets min salary for slider
        SalarySlider.setMaximum(sv[1]); //sets max salary for slider

        SalarySlider.setMajorTickSpacing(sv[2]); //sets major tick spacing 
        SalarySlider.setMinorTickSpacing(sv[3]); //sets minor tick spacing
        //sets the labels on slider
        SalarySlider.setLabelTable(SalarySlider.createStandardLabels(sv[2]));
        
        SalarySlider.setValue(mid);//sets pointer at mid point
    }//end of SetSlider
    
    //*****************************************************
    // Purpose: resets all inputs
    // Interface: IN: na
    // Returns: na
    // *****************************************************
    private void ResetInputs(){
       ResetCityCombo(); //resets city combo box
       ResetPositionCombo(POSL); //resets psoition combo box
       ResetNames(); //resets name fields
       SetSlider(SAL); //resets slider
    }//end of reset inputs
    
    //*****************************************************
    // Purpose: set controller for gui
    // Interface: IN: controller
    // Returns: na
    // *****************************************************
    protected void setController (Controller C){
        this.con = C; //sets controller to new value
    }//end of setController
    
    protected void loadEmployeeListModel(ArrayList<Employee> list){
        employeeListModel.removeAllElements();
        for (Employee e: list){
            employeeListModel.addElement(e);
        }//end of for
        
        con.loadListButtonClicked(list.get(list.size()-1));
    }//end of loadPatientListModel
    
    private void resetIDS(){
        int nextID = 1000;//base id
        
        for(int i = 0; i<con.employees.size(); i++){
            con.employees.get(i).setId(nextID);//sets new id for employee
            nextID++;//adds one to id
        }//end of for
        loadEmployeeListModel(con.employees);//loads list with new values
    }//end of resetIDS
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EmployeeGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EmployeeGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EmployeeGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EmployeeGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EmployeeGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ApplicationLabel;
    private javax.swing.JComboBox<String> CityCombo;
    private javax.swing.JLabel CityLabel;
    private javax.swing.JButton ClearBtn;
    private javax.swing.JButton EditBtn;
    private javax.swing.JLabel EmployeeDetailLabel;
    private javax.swing.JScrollPane EmployeeDetailScrollPane;
    private javax.swing.JTextArea EmployeeDetailTxt;
    private javax.swing.JList<String> EmployeeList;
    private javax.swing.JLabel EmployeeListLabel;
    private javax.swing.JScrollPane EmployeeListScrollPane;
    private javax.swing.JPanel EmployeePanel;
    private javax.swing.JLabel FirstNameLabel;
    private javax.swing.JTextField FirstNameTxt;
    private javax.swing.JPanel InfoPanel;
    private javax.swing.JLabel InfoPanelLabel;
    private javax.swing.JLabel InformationControlsLabel;
    private javax.swing.JLabel LastNameLabel;
    private javax.swing.JTextField LastNameTxt;
    private javax.swing.JButton LoadBtn;
    private javax.swing.JComboBox<String> PositionCombo;
    private javax.swing.JLabel PositionLabel;
    private javax.swing.JButton RemoveBtn;
    private javax.swing.JLabel SalaryLabel;
    private javax.swing.JSlider SalarySlider;
    private javax.swing.JButton SaveBtn;
    private javax.swing.ButtonGroup SearchRB;
    private javax.swing.JButton SubmitBtn;
    // End of variables declaration//GEN-END:variables
}
